### ISSUE TITLE
ValueError: population must be at least size 3 for a pair to be selected

### ISSUE THREAD

**Issue by anderdnavarro** [simonprovost/Auto-Sklong#6]
Hi!

I'm trying to run a `GamaLongitudinalClassifier` using your example code and both your sample dataset and my dataset, but I always get `ValueError: population must be at least size 3 for a pair to be selected`:

This is the code:
```python
# Load the dataset
dataset = LongitudinalDataset('/home/stroke_longitudinal.csv')
dataset.load_data()
dataset.load_target(target_column="stroke_w2")
dataset.load_train_test_split()
dataset.setup_features_group(input_data="elsa")
print(f"Features group: {dataset.feature_groups(names=True)}")
print(f"Non-longitudinal features: {dataset.non_longitudinal_features(names=True)}")

# Features group: [['smoke_w1', 'smoke_w2'], ['cholesterol_w1', 'cholesterol_w2']]
# Non-longitudinal features: ['age', 'gender']

automl = GamaLongitudinalClassifier(
    features_group=dataset.feature_groups(),
    non_longitudinal_features=dataset.non_longitudinal_features(), 
    feature_list_names=dataset.data.columns
)

automl.fit(dataset.X_train, dataset.y_train)
```

This is the first error, that raises several times:
```python
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/scikit_longitudinal/pipeline_managers/manage_errors/manage.py", line 30, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/scikit_longitudinal/pipeline_managers/manage_errors/manage.py", line 30, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/scikit_longitudinal/pipeline_managers/manage_errors/manage.py", line 30, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/scikit_longitudinal/pipeline_managers/manage_errors/manage.py", line 101, in wrapper
    return f(*list_args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/scikit_longitudinal/pipeline_managers/manage_errors/manage.py", line 101, in wrapper
    return f(*list_args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/scikit_longitudinal/pipeline_managers/manage_errors/manage.py", line 101, in wrapper
    return f(*list_args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/scikit_longitudinal/pipeline.py", line 108, in fit
    ) = configure_and_fit_transformer(
  File "/usr/local/lib/python3.9/site-packages/scikit_longitudinal/pipeline.py", line 108, in fit
    ) = configure_and_fit_transformer(
  File "/usr/local/lib/python3.9/site-packages/scikit_longitudinal/pipeline.py", line 108, in fit
    ) = configure_and_fit_transformer(
  File "/usr/local/lib/python3.9/site-packages/scikit_longitudinal/pipeline_managers/manage_steps/manage.py", line 51, in configure_and_fit_transformer
    transformer = configure_transformer(
  File "/usr/local/lib/python3.9/site-packages/scikit_longitudinal/pipeline_managers/manage_steps/manage.py", line 51, in configure_and_fit_transformer
    transformer = configure_transformer(
  File "/usr/local/lib/python3.9/site-packages/scikit_longitudinal/pipeline_managers/manage_steps/manage.py", line 51, in configure_and_fit_transformer
    transformer = configure_transformer(
  File "/usr/local/lib/python3.9/site-packages/scikit_longitudinal/pipeline_managers/utils.py", line 84, in configure_transformer
    check_required_attributes()
  File "/usr/local/lib/python3.9/site-packages/scikit_longitudinal/pipeline_managers/utils.py", line 84, in configure_transformer
    check_required_attributes()
  File "/usr/local/lib/python3.9/site-packages/scikit_longitudinal/pipeline_managers/utils.py", line 84, in configure_transformer
    check_required_attributes()
  File "/usr/local/lib/python3.9/site-packages/scikit_longitudinal/pipeline_managers/utils.py", line 55, in check_required_attributes
    if not feature_list_names:
  File "/usr/local/lib/python3.9/site-packages/scikit_longitudinal/pipeline_managers/utils.py", line 55, in check_required_attributes
    if not feature_list_names:
  File "/usr/local/lib/python3.9/site-packages/scikit_longitudinal/pipeline_managers/utils.py", line 55, in check_required_attributes
    if not feature_list_names:
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3188, in __nonzero__
    raise ValueError(
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3188, in __nonzero__
    raise ValueError(
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3188, in __nonzero__
    raise ValueError(
ValueError: The truth value of a Index is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
ValueError: The truth value of a Index is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
ValueError: The truth value of a Index is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/scikit_longitudinal/pipeline_managers/manage_errors/manage.py", line 30, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/scikit_longitudinal/pipeline_managers/manage_errors/manage.py", line 30, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/scikit_longitudinal/pipeline_managers/manage_errors/manage.py", line 101, in wrapper
    return f(*list_args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/scikit_longitudinal/pipeline_managers/manage_errors/manage.py", line 101, in wrapper
    return f(*list_args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/scikit_longitudinal/pipeline.py", line 108, in fit
    ) = configure_and_fit_transformer(
  File "/usr/local/lib/python3.9/site-packages/scikit_longitudinal/pipeline.py", line 108, in fit
    ) = configure_and_fit_transformer(
  File "/usr/local/lib/python3.9/site-packages/scikit_longitudinal/pipeline_managers/manage_steps/manage.py", line 51, in configure_and_fit_transformer
    transformer = configure_transformer(
  File "/usr/local/lib/python3.9/site-packages/scikit_longitudinal/pipeline_managers/manage_steps/manage.py", line 51, in configure_and_fit_transformer
    transformer = configure_transformer(
  File "/usr/local/lib/python3.9/site-packages/scikit_longitudinal/pipeline_managers/utils.py", line 84, in configure_transformer
    check_required_attributes()
  File "/usr/local/lib/python3.9/site-packages/scikit_longitudinal/pipeline_managers/utils.py", line 84, in configure_transformer
    check_required_attributes()

An error occurred in function fit: The truth value of a Index is ambiguous. Use a.empty, a.bool(), a.item(), 
a.any() or a.all().
```

This is the last error:
```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[36], [line 1](vscode-notebook-cell:?execution_count=36&line=1)
----> [1](vscode-notebook-cell:?execution_count=36&line=1) automl.fit(dataset.X_train, dataset.y_train)

File /usr/local/lib/python3.9/site-packages/gama/GamaLongitudinalClassifier.py:384, in GamaLongitudinalClassifier.fit(self, x, y, *args, **kwargs)
    [381](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/GamaLongitudinalClassifier.py:381)     if "labels" in inspect.signature(m.scorer._score_func).parameters:
    [382](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/GamaLongitudinalClassifier.py:382)         m.scorer._kwargs.update({"labels": y})
--> [384](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/GamaLongitudinalClassifier.py:384) super().fit(
    [385](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/GamaLongitudinalClassifier.py:385)     x=x,
    [386](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/GamaLongitudinalClassifier.py:386)     y=y,
    [387](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/GamaLongitudinalClassifier.py:387)     basic_encoding_step=False,
    [388](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/GamaLongitudinalClassifier.py:388)     fixed_encoding_step=False,
    [389](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/GamaLongitudinalClassifier.py:389)     *args,
    [390](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/GamaLongitudinalClassifier.py:390)     **kwargs,
    [391](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/GamaLongitudinalClassifier.py:391) )

File /usr/local/lib/python3.9/site-packages/gama/gama.py:657, in Gama.fit(self, x, y, warm_start, basic_encoding_step, fixed_encoding_step)
    [647](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/gama.py:647) fit_time = int(
    [648](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/gama.py:648)     (1 - self._post_processing.time_fraction)
    [649](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/gama.py:649)     * self._time_manager.total_time_remaining
    [650](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/gama.py:650) )
    [652](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/gama.py:652) with self._time_manager.start_activity(
    [653](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/gama.py:653)     "search",
    [654](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/gama.py:654)     time_limit=fit_time,
    [655](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/gama.py:655)     activity_meta=[self._search_method.__class__.__name__],
    [656](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/gama.py:656) ):
--> [657](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/gama.py:657)     self._search_phase(warm_start, timeout=fit_time)
    [659](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/gama.py:659) with self._time_manager.start_activity(
    [660](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/gama.py:660)     "postprocess",
    [661](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/gama.py:661)     time_limit=int(self._time_manager.total_time_remaining),
    [662](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/gama.py:662)     activity_meta=[self._post_processing.__class__.__name__],
    [663](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/gama.py:663) ):
    [664](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/gama.py:664)     best_individuals = list(
    [665](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/gama.py:665)         reversed(
    [666](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/gama.py:666)             sorted(
   (...)
    [670](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/gama.py:670)         )
    [671](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/gama.py:671)     )

File /usr/local/lib/python3.9/site-packages/gama/gama.py:717, in Gama._search_phase(self, warm_start, timeout)
    [715](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/gama.py:715)     with stopit.ThreadingTimeout(timeout):
    [716](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/gama.py:716)         self._search_method.dynamic_defaults(self._x, self._y, timeout)
--> [717](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/gama.py:717)         self._search_method.search(self._operator_set, start_candidates=pop)
    [718](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/gama.py:718) except KeyboardInterrupt:
    [719](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/gama.py:719)     log.info("Search phase terminated because of Keyboard Interrupt.")

File /usr/local/lib/python3.9/site-packages/gama/search_methods/async_ea.py:70, in AsyncEA.search(self, operations, start_candidates)
     [67](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/search_methods/async_ea.py:67) def search(
     [68](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/search_methods/async_ea.py:68)     self, operations: OperatorSet, start_candidates: List[Individual]
     [69](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/search_methods/async_ea.py:69) ) -> None:
---> [70](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/search_methods/async_ea.py:70)     self.output = async_ea(
     [71](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/search_methods/async_ea.py:71)         operations, self.output, start_candidates, **self.hyperparameters
     [72](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/search_methods/async_ea.py:72)     )

File /usr/local/lib/python3.9/site-packages/gama/search_methods/async_ea.py:163, in async_ea(ops, output, start_candidates, restart_callback, max_n_evaluations, population_size, max_attempts)
    [154](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/search_methods/async_ea.py:154)         current_population.remove(to_remove[0])
    [156](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/search_methods/async_ea.py:156) if async_.job_queue_size <= 1:
    [157](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/search_methods/async_ea.py:157)     # Technically 0 should work to keep near-100% worker load,
    [158](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/search_methods/async_ea.py:158)     # especially if the dataset is sufficiently large to require
   (...)
    [161](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/search_methods/async_ea.py:161)     # but also increases information lag. An offspring created too
    [162](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/search_methods/async_ea.py:162)     # early might miss out on a better parent.
--> [163](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/search_methods/async_ea.py:163)     new_individual = generate_unique_individual(
    [164](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/search_methods/async_ea.py:164)         ops, lambda: ops.create(current_population, 1)[0], max_attempts
    [165](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/search_methods/async_ea.py:165)     )
    [166](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/search_methods/async_ea.py:166)     async_.submit(ops.evaluate, new_individual)
    [168](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/search_methods/async_ea.py:168) should_restart = restart_callback is not None and restart_callback()

File /usr/local/lib/python3.9/site-packages/gama/search_methods/async_ea.py:80, in generate_unique_individual(ops, generator_function, max_attempts)
     [78](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/search_methods/async_ea.py:78) """Generate a unique individual using the given generator function"""
     [79](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/search_methods/async_ea.py:79) attempts = 0
---> [80](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/search_methods/async_ea.py:80) while (new_individual := generator_function()) and ops.is_evaluated(
     [81](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/search_methods/async_ea.py:81)     new_individual
     [82](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/search_methods/async_ea.py:82) ):  # type: ignore
     [83](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/search_methods/async_ea.py:83)     if attempts >= max_attempts:
     [84](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/search_methods/async_ea.py:84)         raise ValueError(
     [85](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/search_methods/async_ea.py:85)             "Maximum attempts reached while trying to generate a"
     [86](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/search_methods/async_ea.py:86)             "unique individual."
     [87](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/search_methods/async_ea.py:87)         )

File /usr/local/lib/python3.9/site-packages/gama/search_methods/async_ea.py:164, in async_ea.<locals>.<lambda>()
    [154](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/search_methods/async_ea.py:154)         current_population.remove(to_remove[0])
    [156](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/search_methods/async_ea.py:156) if async_.job_queue_size <= 1:
    [157](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/search_methods/async_ea.py:157)     # Technically 0 should work to keep near-100% worker load,
    [158](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/search_methods/async_ea.py:158)     # especially if the dataset is sufficiently large to require
   (...)
    [161](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/search_methods/async_ea.py:161)     # but also increases information lag. An offspring created too
    [162](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/search_methods/async_ea.py:162)     # early might miss out on a better parent.
    [163](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/search_methods/async_ea.py:163)     new_individual = generate_unique_individual(
--> [164](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/search_methods/async_ea.py:164)         ops, lambda: ops.create(current_population, 1)[0], max_attempts
    [165](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/search_methods/async_ea.py:165)     )
    [166](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/search_methods/async_ea.py:166)     async_.submit(ops.evaluate, new_individual)
    [168](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/search_methods/async_ea.py:168) should_restart = restart_callback is not None and restart_callback()

File /usr/local/lib/python3.9/site-packages/gama/genetic_programming/operator_set.py:97, in OperatorSet.create(self, *args, **kwargs)
     [96](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/genetic_programming/operator_set.py:96) def create(self, *args, **kwargs) -> List[Individual]:
---> [97](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/genetic_programming/operator_set.py:97)     return self._create_from_population(self, *args, **kwargs)

File /usr/local/lib/python3.9/site-packages/gama/genetic_programming/longitudinal/selection_longitudinal.py:26, in create_longitudinal_from_population(operator_shell, pop, n, cxpb, mutpb)
     [24](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/genetic_programming/longitudinal/selection_longitudinal.py:24) offspring = []
     [25](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/genetic_programming/longitudinal/selection_longitudinal.py:25) metrics = [lambda ind: ind.fitness.values[0], lambda ind: ind.fitness.values[1]]
---> [26](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/genetic_programming/longitudinal/selection_longitudinal.py:26) parent_pairs = nsga2_select(pop, n, metrics)
     [27](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/genetic_programming/longitudinal/selection_longitudinal.py:27) for ind1, ind2 in parent_pairs:
     [28](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/genetic_programming/longitudinal/selection_longitudinal.py:28)     if (
     [29](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/genetic_programming/longitudinal/selection_longitudinal.py:29)         random.random() < cxpb
     [30](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/genetic_programming/longitudinal/selection_longitudinal.py:30)         and len(_valid_longitudinal_crossover_functions(ind1, ind2)) > 0
     [31](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/genetic_programming/longitudinal/selection_longitudinal.py:31)     ):

File /usr/local/lib/python3.9/site-packages/gama/genetic_programming/nsga2.py:49, in nsga2_select(population, n, metrics)
     [42](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/genetic_programming/nsga2.py:42) """Select n pairs from the population.
     [43](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/genetic_programming/nsga2.py:43) 
     [44](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/genetic_programming/nsga2.py:44) Selection is done through binary tournament selection based on crowding distance.
     [45](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/genetic_programming/nsga2.py:45) Parent pairs may be repeated, but each parent pair consists of two unique parents.
     [46](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/genetic_programming/nsga2.py:46) The population must be at least size 3 (otherwise it is trivial or impossible).
     [47](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/genetic_programming/nsga2.py:47) """
     [48](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/genetic_programming/nsga2.py:48) if len(population) < 3:
---> [49](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/genetic_programming/nsga2.py:49)     raise ValueError("population must be at least size 3 for a pair to be selected")
     [51](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/genetic_programming/nsga2.py:51) # Entire population is returned, but with rank and distance information.
     [52](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/python3.9/site-packages/gama/genetic_programming/nsga2.py:52) candidates = nsga2(population, n=len(population), metrics=metrics, return_meta=True)

ValueError: population must be at least size 3 for a pair to be selected
```

I don't know if the last error can be related to the first one.

I'm using `python3.9` and these modules versions:
```bash
scikit-lexicographical-trees==0.0.4
Scikit-longitudinal==0.0.6
scipy==1.13.1
```

Thanks a lot!!
Ander

**Comment by simonprovost** [comment]
Hi, Mate! I will respond in a few days; I am attending a conference this week. No worries, your errors are not uncommon; I will explain how to correct them. In the meantime, would you mind sharing your dataset as a CSV file so that I can recreate it? If this is highly sensitive data. Simply reproduce one raw with random values or two raws but most importantly with the same features, change the name but keep the same amount, and I will be able to mirror the issue if I can not figure out how to do it without.

Cheers,

**Comment by anderdnavarro** [comment]
Hi!

I've prepared a sample dataset for you, same features but with the name changed. It is prepared to be imported with `dataset.setup_features_group(input_data="elsa")`. However, I also have the issue with your "stroke" dataset.

[test.csv](https://github.com/user-attachments/files/17002571/test.csv)

Thanks!!
Ander

**Comment by simonprovost** [comment]
Hi @anderdnavarro,

Hope you’re doing well!

It seems there are two main issues causing the problem you described:

1. Number of Samples

The dataset you are using likely has too few samples. To resolve this, I recommend increasing the number of samples in your dataset. As a quick workaround, you can duplicate your existing samples to ensure you have at least 100 samples to work with. While this is not ideal for real scenarios, it should help address the issue for testing purposes.

2. Feature List Names Must Be a List

The `feature_list_names` parameter needs to be explicitly set as a list. Update your code from:

`feature_list_names = dataset.data.columns`

to:

`feature_list_names = dataset.data.columns.tolist()`

This change will ensure the feature names are correctly formatted.

_Additional Notes:_

For debugging or lesser use cases, you may wish to begin with `RandomSearch()` (via the `search` parameter), which is more simple and avoid creating side effects to better localise your error.

I will close this issue for the time being, as the issue should be handled by increasing the amount of samples and modifying the feature_list_names parameter. Feel free to reopen if you continue to have problems.

Cheers,

**Comment by simonprovost** [comment]
New release `0.0.3` is now available! 🎉 The major change is the migration from `PDM` to `UV` for easier and faster installation. However, I used the opportunity to improve the documentation slightly, particularly in terms of feature list names issue in the quick start pseudo-code as you pointed out and explaining better the installation on Apple silicon-based Macs.

Have a peek at the releases and the documentation! Thanks for your help showing them out!

_Note: Will apply the same migration and doc. refactor to `Sklong` as soonish as possible!_

Cheers,
